INSERT INTO elms.courses (id, code, name, units) VALUES (12, 'CC111', 'Introduction to Computing', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (13, 'CS101', 'Fundamentals of Programming', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (17, 'GE07', 'Filipino sa ibat-ibang disiplina at Komunikasyon', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (29, 'FIN212', 'Financial Management', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (30, 'CC114', 'Data Structures and Algorithm', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (31, 'CS112', 'Fundamentals of Programming', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (32, 'CS111', 'Discrete Structures 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (33, 'GE713', 'Kontekswalisadong Komunikasyon sa Filipino (KOMFIL)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (34, 'GE701', 'Mathematics in the modern world', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (35, 'GE706', 'Art Appreciation', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (36, 'PE101', 'Physical Fitness and Self-Testing Activities', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (37, 'NSTP101', 'National Service Training Program 1', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (38, 'CS113', 'Intermediate Programming', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (39, 'CS122', 'Discrete Structures 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (40, 'MATH005', 'Analytic Geometry', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (41, 'GE715', 'Filipino sa ibat-ibang displinal (FILDIS)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (42, 'GE702', 'Purposived Communication', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (43, 'GE708', 'Understanding the self', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (44, 'PE102', 'Rhythmic Activities', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (45, 'NSTP102', 'National Service Training Program 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (46, 'CC112', 'Computer Programming 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (47, 'IS111', 'Fundamentals of Information Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (48, 'ACCTG111', 'Financial Accounting and Reporting', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (49, 'CC113', 'Computer Programming 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (50, 'IS121', 'IT Infrastructure and Network Technologies', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (51, 'IS122', 'Organization and Management Concepts', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (52, 'ACCTG 121', 'Basic Accounting for Partnership and Corporate Entities', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (55, 'OOP212', 'Object-Oriented Programming', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (56, 'CC114', 'Data Structures and Algorithm', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (57, 'AR214', 'Architecture and Organization', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (58, 'AI215', 'Artificial Intelligence', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (59, 'MATH110', 'Calculus', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (60, 'GE705', 'The Contemporary World', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (61, 'GE703', 'Ethics', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (62, 'PE103', 'Team Sports', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (63, 'AC221', 'Algorithms and Complexity', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (64, 'PL222', 'Programming Languages', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (65, 'OS223', 'Operating Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (66, 'CC115', 'Information Management', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (67, 'NC225', 'Networks and Communication', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (68, 'GE709', 'The Life and works of Rizal', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (69, 'GE704', 'Science, Technology and Society', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (70, 'PE104', 'Recreational Activities', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (71, 'ALT312', 'Automata Theory and Formal Languages', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (72, 'SE314', 'Software Engineering 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (73, 'CC315', 'Applications Development and Emerging Technology', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (74, 'HCI316', 'Human Computer Interaction', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (75, 'CSELECT 1', 'System Fundamentals', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (76, 'DC313', 'Digital Design', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (77, 'STAT003', 'Statistics with Computer Application', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (78, 'ENG001', 'Advanced Technical Writing', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (79, 'SE324', 'Software Engineering 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (80, 'FTS321', 'Filed Trip and Seminars', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (81, 'RES111', 'Methods of Research', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (82, 'IAS327', 'Information Assurance and Security', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (83, 'CSELECT2', 'Computational Science', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (84, 'CSELECT3', 'Intelligent Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (85, 'CS300', 'Practicum (162 hours)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (86, 'CS400', 'CS Thesis Writing 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (87, 'CSELECT4', 'Parallel and Distributed Computing', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (88, 'GE711', 'Cultures of Mindanao', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (89, 'GE712', 'Gender and Society', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (90, 'GE707', 'Readings in Philippine History', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (91, 'CS450', 'CS Thesis Writing 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (92, 'SPI411S', 'Social Issues and Professional Practice', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (93, 'IS111', 'IS Fundamentals', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (94, 'IS112', 'Office Productivity', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (95, 'FIL111', 'Komunikasyon sa Akademikong Filipino', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (96, 'ENG111', 'Communication Arts', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (97, 'MATH111', 'College Algebra', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (98, 'HUM111', 'Intro. to Humanities', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (99, 'PSYCHO116', 'General Psychology', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (100, 'PE111', 'Physical Fitness', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (101, 'NSTP1', 'NSTP I', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (102, 'IS113', 'Human Computer Interaction', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (103, 'IS114', 'Programming', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (104, 'IS115', 'Ethics for IT Professionals', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (105, 'IS116', 'Fundamental of Management and Business', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (106, 'ENG112', 'Writing in the Discipline', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (107, 'FIL112', 'Pagbasa at Pagsulat Tungo sa Pananaliksik', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (108, 'MATH112', 'Plane Trigonometry', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (109, 'PE112', 'Rhythmic Activities', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (110, 'NSTP2', 'NSTP II', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (111, 'IS117', 'System Infrastructure and Integration', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (112, 'IS118', 'System Analysis and Design', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (113, 'IS119', 'Database Management Systems (DBMS)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (114, 'IS120', 'Business Processes and Analysis of Business Performance', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (115, 'IS121', 'Discrete Structure', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (116, 'FIL113', 'Masining na Pagpapahayag', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (117, 'ENG113', 'Speech and Oral Communication', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (118, 'PHYS100', 'Applied Physics I', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (119, 'PE113', 'Team Sports', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (120, 'IS122', 'Applications Development', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (121, 'IS123', 'Web Development', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (122, 'IS124', 'Networks and Internet Technology', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (123, 'LIT111', 'Philippine Literature', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (124, 'ACCTG111', 'Basic Accounting', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (125, 'STAT111', 'Intro. to Statistics', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (126, 'PHYS200', 'Applied Physics II', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (127, 'PE114', 'Recreational Activities', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (128, 'IS125', 'Deployment Maintenance and Services', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (129, 'IS126', 'IT Project Management and Quality Assessment', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (130, 'IS127', 'Evaluation of Business Performance', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (131, 'ACCTG112', 'Accounting and Financials', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (132, 'ISELEC1', 'Elective1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (133, 'FREEELEC1', 'Free Elective 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (134, 'ENG114', 'Technical Writing and Reporting', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (135, 'ECON111', 'Principles of Economics with  Taxation', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (136, 'IS128', 'Information Systems Planning', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (137, 'IS129', 'Management of Technology', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (138, 'ISELEC2', 'Elective2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (139, 'ISELEC3', 'Elective3', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (140, 'FREEELEC2', 'Free Elective 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (141, 'RES111', 'IS Research Methods', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (142, 'SOCSCI132', 'Life and Works of Rizal and Other Heroes', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (143, 'FTS', 'Field Trip and Seminars', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (144, 'IS130', 'Industry Immersion', 9);
INSERT INTO elms.courses (id, code, name, units) VALUES (145, 'IS131', 'Capstone Project', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (146, 'ISELEC4', 'Elective 4', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (147, 'FREEELEC3', 'Free Elective 3', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (148, 'FREEELEC4', 'Free Elective 4', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (149, 'IS133', 'Technopreneurship', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (150, 'IT111', 'IT Fundamentals', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (151, 'IT101', 'Programming I', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (152, 'IT112', 'Office Productivity', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (154, 'IT114', 'Computer Organization', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (155, 'IT115', 'Discrete Structure', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (156, 'IT103', 'Programming III', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (157, 'IT102', 'Programming II', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (158, 'IT113', 'Ethics for IT Professionals', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (159, 'IT116', 'Database Management System I', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (160, 'IT120', 'Operating System Applications', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (161, 'IT118', 'System Analysis and Design I', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (162, 'IT121', 'Network Management', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (163, 'IT122', 'Web Development', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (164, 'IT117', 'Database Management System II', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (165, 'IT119', 'Systems Analysis and Design II', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (166, 'ITELEC 1', 'Elective1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (171, 'PHILOS111', 'Intro. to Logic', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (172, 'HIST111', 'Phil.  History and Culture', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (173, 'IT123', 'Multimedia Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (174, 'IT124', 'Software Engineering', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (175, 'ITELEC 2', 'Elective2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (179, 'IT125', 'Technopreneurship', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (181, 'IT400', 'Internship/Practicum/OJT', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (182, 'ITELEC3', 'Elective3', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (183, 'ITELEC4', 'Elective 4', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (184, 'IT401', 'Capstone Project', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (186, 'SOCIO111', 'Society and Culture with FP', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (187, 'POLSCI111', 'Philippine Constitution and Governance', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (188, 'ACCTG111', 'Accounting 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (189, 'ACCTG121', 'Accounting 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (190, 'ELECT1', 'Elective 1 (Customer Relationship Management)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (191, 'IS212', 'Financial Management', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (192, 'PE103', 'Recreational Activities (Individual and Dual)', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (193, 'PE104', 'Team Sports', 2);
INSERT INTO elms.courses (id, code, name, units) VALUES (194, 'IS221', 'Systems Analysis and Design', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (195, 'IS222', 'Enterprise Architecture', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (196, 'IS223', 'Business Process and Management', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (197, 'ELECT2', 'Elective 2 (Data Mining)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (198, 'IS311', 'Evaluation of Business Performance', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (199, 'IS312', 'System Infrastructure and Integration', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (200, 'IS313', 'IS Project Management 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (201, 'IS323', 'Quantitative Methods', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (202, 'ELECT3', 'Elective (Supply Chain Management)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (203, 'IS314', 'Professional Issues in Information Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (204, 'IS321', 'Managment Information System', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (205, 'IS322', 'Capstone Project 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (206, 'IS324', 'Information Systems Policy', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (207, 'CC116', 'Application Development and Emerging Technologies', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (208, 'IS412', 'Capstone Project 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (209, 'IS421', 'Practicum for Information Systems (486 hours)', 6);
INSERT INTO elms.courses (id, code, name, units) VALUES (210, 'ELECT 4', 'Elective IV (Business Intelligence)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (211, 'IS411', 'Is Strategy, Management and Acquisition', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (212, 'MS121', 'Discrete Mathematics', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (213, 'IM121', 'Fundamentals of Database Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (214, 'PF211', 'Object-Oriented Programmin', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (215, 'PT212', 'Platform Technologies', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (216, 'WS213', 'Web Systems and Technologies', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (217, 'PF221', 'Event-Driven Programming', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (218, 'IPT225', 'Integrative Programming and Technologies 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (219, 'IM223', 'Advanced Database Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (220, 'HCI221', 'Introduction to Human Computer Interaction', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (221, 'MS312', 'Quantitative Methods (including Modeling and Simulation)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (222, 'IPT313', 'Interactive Programming and Technologies 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (223, 'IAS314', 'Information Assurance and Security 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (224, 'IAS322', 'Information Assurance and Security 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (225, 'SIA317', 'Systems Integration and Architecture 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (226, 'AT316', 'Digital Design', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (227, 'NET321', 'Networking 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (228, 'NET311', 'Networking 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (229, 'AT324', 'Embedded Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (230, 'CAP325', 'Capstone Project and Research 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (231, 'SP326', 'Social and Professional Issues', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (232, 'AT327', 'Mobile Computing', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (233, 'CAP420', 'Capstone Project and Research 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (234, 'SA421', 'System Administration and Maintenance', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (235, 'ACCTG210', 'Fundamentals of Accounting', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (236, 'ACCTG220', 'Financial Management', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (237, 'PRACTI 101', 'Practicum (486 hours)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (238, 'IT103', 'Programming 3', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (239, 'ENG112', 'Writing in Discipline', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (240, 'APC211', 'Graphics and Multimedia Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (241, 'CS101', 'Programming 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (243, 'CS102', 'Programming II', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (246, 'CS112', 'Data Structures', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (247, 'CS113', 'Ethics for IT Professionals', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (248, 'CS103', 'Programming III', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (249, 'CS114', 'Discrete Structure', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (250, 'CS115', 'Design and Analysis of Algorithm', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (251, 'MATH113', 'Analytic Geometry', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (252, 'CS104', 'Programmin IV', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (253, 'CS116', 'Database Systems', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (254, 'CS117', 'Programming Languages', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (255, 'CS118', 'Digital Design', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (256, 'CS111', 'CS Fundamentals', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (257, 'PHYS1', 'General Physics I', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (258, 'PHYS2', 'General Physics 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (260, 'MATH114', 'Calculus', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (261, 'CS119', 'Computer Organization and Assembly Lab', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (262, 'CS120', 'Automata and Language Theory', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (263, 'CS121', 'Modeling and Simulation', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (266, 'ENG114', 'Technical Writing and Reporting', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (267, 'HUM111', 'Introduction to Humanities', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (268, 'MATH115', 'Probability and Statistics', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (269, 'CS123', 'System Analysis and Design', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (270, 'CS124', 'Operating System', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (272, 'CSELECT2', 'CS Elect 2', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (273, 'FREEELEC1', 'Free Elective 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (274, 'HIST111', 'Phil. History and Culture', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (276, 'RES111', 'CS Research Methods', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (278, 'CS300', 'Internship/Practicum/OJT', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (279, 'CS132', 'Networking Principles', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (281, 'CS400', 'Thesis 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (282, 'CSELECT3', 'CS Elective 3', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (283, 'POLSCI111', 'Philippine Constitution and Governance', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (284, 'CS450', 'Thesis II', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (285, 'CSELECT4', 'CS Elective 4', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (287, 'CS122', 'Web Programming', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (288, 'CSELECT1', 'CS Elective 1', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (289, 'CS300', 'Practicum (162 hours)', 3);
INSERT INTO elms.courses (id, code, name, units) VALUES (290, 'CS451', 'Artificial Intelligence', 3);